from Controller import *
from openal import *

class View:
    def __init__(self):
        self.sections = []
        self.sections.append(Section(0, "Bienvenid@ a 'The lost destiny'.", [("Start", 2), ("Instructions", 1), ("Exit", -1)], Audio("./ambient/intro.wav"), None))
        self.sections.append(Section(1, "En este juego, tu objetivo es sobrevivir en un mundo desconocido y encontrar tu camino a casa.\n Tienes que tomar decisiones para avanzar y evitar morir. Buena suerte.", [("Go back", 0)], Audio("./ambient/instructions.wav"), None))
        self.sections.append(Section(2, "Te encuentras en medio de un bosque, sin saber que sucedió. \nLa única cosa que recuerdas es que estabas escapando de alguien... no recuerdas nada más.\n\nEstá lloviendo, el clima es muy frío. Tratas de buscar un refugio. \nDespués de caminar por 5 minutos te encuentras con tres caminos. Además, escuchas unos pasos a tu derecha, ¡Alguien se acerca!.", [("Camino derecho", 3), ("Camino del frente", 4), ("Camino izquierdo", 5), ("Esperar", 6)], Audio("./ambient/foreststorm.wav"), Audio("./sfx/running_leaves.wav", 1, [1, 0, 0], [-2, 0, 0])))
        self.sections.append(Section(3, "Eliges el camino derecho. \nDespués de caminar por 2 horas, te encuentras con una vieja choza de madera. \nDecides entrar sin pensar si alguien se encuentra adentro. Afortunadamente, no hay nadie.\n\nInvestigas un poco, encontrando comida, agua, y una chimenea con poca leña en el rincón izquierdo de la casa. Hay una cama, se ve cómoda.\n\nPor alguna razón, sientes que has sellado tu destino...", [("Dormir", 4)], Audio("./ambient/hut.wav"), Audio("./sfx/chimney.wav", 4, (-5, 0, 0))))
        self.sections.append(Section(4, "Estás durmiendo. Sueñas que te encuentras en una cueva sin escapatoria. \nEscuchas voces extrañas. Sientes una sensacion de no tener salida", [("¡Despierta!", 5)], Audio("./ambient/snore.wav"), Audio("./sfx/ghost.wav")))
        self.sections.append(Section(5, "Despiertas en... ¿QUÉ LUGAR ES ESTE? \nTe encuentras con los brazos atados en una silla. En frente tuyo están 2 soldados...\n\n- Con que ya despertaste. Mira, no sabemos quien eres, pero por lo visto pareces un espía, más te vale dar explicaciones si no quieres que te matemos...", [("No se de que hablan. Me perdí en el bosque. Necesito ayuda para encontrar mi camino a casa.", 7), ("¡Sueltenme, no soy ningún espía!", 7), ("(Pretender) ¡Ja, ustedes nunca podrán derrotarnos!", 6)], Audio(""), Audio("")))
        self.sections.append(Section(6, "Sin poder decir más, los soldados abren fuego y mueres...", [("Ouch...", -1)]))
        self.sections.append(Section(7, "- Eso lo veremos después. Pero por ahora, puedes sernos útil, jejeje. \nVerás, estamos en guerra con la nación vecina. Vamos perdiendo en vidas, pero tenemos la ventaja tecnológica. \nSi nos ayudas, tal vez podamos recompensarte con lo que buscas... \nTu objetivo es sencillo. Presta atención a tus alrededores y dispara a los soldados antes de que te maten. ¿Qué dices?", [("Si.", 8), ("No.", 6)], Audio(""), Audio("")))
        self.sections.append(Section(9, "Haz fallado la dirección. El soldado se percata de tu presencia y te mata...", [("Nooo....", -1)], Audio(""), Audio("")))
        self.sections.append(Section(10, "- ¡Felicidades! Fuiste de gran ayuda. Hemos ganado la guerra. Como recompensa, te indicaremos el camino a casa. Y para responder tu pregunta... \nEste es un mundo al que llegan los fracasados. Si estás aquí es porque en algún momento de tu vida decidiste rendirte y no continuar...\n Nosotros estamos en esta guerra desde hace más de 4 mil años, sin poder avanzar en ella porque todos nuestros soldados se rinden antes de luchar y vencer al enemigo. \nSin embargo, tu demostraste perseverancia, decidiste ayudarnos y encontrar tu camino de vuelta. \nYa no tienes por qué estar aquí. Puedes volver a tu hogar como si nada de esto hubiera sucedido...", [("Volver a casa"), -2], Audio(""), Audio("")))
        c = Controller(self.sections)
        c.startGame()